version: "3.4"

services:
  app:
    build: .
    container_name: portfolio_container
    command: gunicorn Portfolio.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./staticfiles:/tmp/Portfolio/staticfiles/
    ports:
      - 8000:8000
    env_file:
      - Portfolio/.env

  nginx:
    image: nginx
    container_name: nginx_container
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./staticfiles:/home/app/web/staticfiles/
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - app

  certbot:
    image: certbot/certbot:latest
    container_name: certbot_container
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw



