version: "3.4"

services:
  certbot:
    image: certbot/certbot:latest
    container_name: certbot_container
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw



