version: "3.4"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio_app
    command: gunicorn --bind 0.0.0.0:8000 portfolio.wsgi:application
    volumes:
      - ./staticfiles:/tmp/Portfolio/staticfiles/
    ports:
      - 8000:8000
    env_file:
      - Portfolio/.env

  nginx:
    image: nginx
    container_name: web_server
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./staticfiles:/home/app/web/staticfiles/
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - app
