# Generated by Django 4.1.7 on 2023-02-26 12:45

import django.core.validators
from django.db import migrations, models
import support.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2, message='Must be at least 2 chars long.'), django.core.validators.MaxLengthValidator(30, message='Must be no more than 30 chars long.'), support.validators.check_if_letters_only], verbose_name='Subject')),
                ('full_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2, message='Must be at least 2 chars long.'), django.core.validators.MaxLengthValidator(30, message='Must be no more than 30 chars long.'), support.validators.check_if_letters_only], verbose_name='Full Name')),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='Email')),
                ('number', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2, message='Must be at least 10 digits long.'), django.core.validators.MaxLengthValidator(30, message='Must be no more than 16 chars long.'), support.validators.check_if_digits_only], verbose_name='Contact Number')),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(2, message='Must be at least 10 chars long.')], verbose_name='Message')),
            ],
            options={
                'db_table': 'Contact_Model_Table',
            },
        ),
    ]
