# Generated by Django 4.1.7 on 2023-05-21 12:33

import django.core.validators
from django.db import migrations, models
import support.validators


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0003_alter_contactmodel_message_alter_contactmodel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='full_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2, message='Must be at least 2 chars long.'), django.core.validators.MaxLengthValidator(30, message='Must be no more than 30 chars long.'), support.validators.check_if_full_name], verbose_name='Full Name'),
        ),
    ]
