
name: "Project Code Scanning"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze_code:
    name: "Analyze code"
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ python ]


    steps:
      - name: "Checkout Repo"
        uses: actions/checkoutv@2

      - name: "Init CodeQL"
        uses: github/codeql-action/initv@1
        with:
          languages: ${{ matrix.language }}

      - name: "Autobuild"
        uses: github/codeql-action/autobuild@v1

